[_]
schema-version = "0.2"
id = "com.github.xsavikx.python_functions_cloud_run_buildpacks"
name = "Cloud Run Buildpacks Example"
authors = ["Yurii Serhiichuk <savik.ne@gmail.com>"]
version = "1.0.0"
source-url = "https://github.com/xSAVIKx/python-functions-cloud-run-buildpacks"
documentation-url = "https://github.com/xSAVIKx/python-functions-cloud-run-buildpacks/blob/master/README.md"

[[_.licenses]]
type = "Apache-2.0"
uri = "https://github.com/xSAVIKx/python-functions-cloud-run-buildpacks/blob/master/LICENSE"

[io.buildpacks]
include = [
    "python_functions_cloud_run_buildpacks",
    "main.py",
    "pyproject.toml",
    "requirements.txt",
    "LICENSE"
]

[[io.buildpacks.build.env]]
name = "GOOGLE_FUNCTION_TARGET"
value = "handle"

[[io.buildpacks.build.env]]
name = "GOOGLE_FUNCTION_SIGNATURE_TYPE"
value = "http"

[[io.buildpacks.build.env]]
name = "GOOGLE_FUNCTION_SOURCE"
value = "main.py"

[[io.buildpacks.build.env]]
name = "GOOGLE_RUNTIME"
value = "python"

[[io.buildpacks.build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "3.11.3"
