[project]
schema-version = "0.2"
id = "com.github.xsavikx.python_functions_cloud_run_buildpacks"
name = "Cloud Run Buildpacks Example"
authors = ["Yurii Serhiichuk <savik.ne@gmail.com>"]
version = "1.0.0"

[io.buildpacks]
include = [
    "python_functions_cloud_run_buildpacks",
    "main.py",
    "project.toml",
    "pyproject.toml",
    "poetry.lock",
    "requirements.txt",
    "poetry.toml"
]

[[io.buildpacks.group]]
id = "google.python.runtime"

  [io.buildpacks.group.script]
  api = "0.6"
  inline = "ls -la /workspace"

[[io.buildpacks.group]]
id = "google.python.functions-framework"

  [io.buildpacks.group.script]
  api = "0.6"
  inline = "ls -la /workspace"

[[io.buildpacks.group]]
id = "google.python.pip"

  [io.buildpacks.group.script]
  api = "0.6"
  inline = "ls -la /workspace"

[[build.env]]
name = "GOOGLE_FUNCTION_TARGET"
value = "handle"

[[build.env]]
name = "GOOGLE_FUNCTION_SIGNATURE_TYPE"
value = "http"

[[build.env]]
name = "GOOGLE_FUNCTION_SOURCE"
value = "main.py"

[[build.env]]
name = "GOOGLE_RUNTIME"
value = "python"

[[build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "3.11.3"
